version: '3.7'
services:
  registry:
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    environment:
      REGISTRY_HTTP_SECRET: secret
      # If you want to change the port the registry listens on within the container
      # REGISTRY_HTTP_ADDR: "0.0.0.0:5001"
    volumes:
      - ./storage/registry:/var/lib/registry
  redis:
    image: redis
